# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2016, 10, 26, 12, 19, 41, 481564)),
        ),
    ]
