# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161026_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_Engagements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('date_order', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
